// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbjevteapkuumqwsnbvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpiamV2dGVhcGt1dW1xd3NuYnZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNjc4ODIsImV4cCI6MjA2NDc0Mzg4Mn0.-Ept9cuSwqhEbfi0RpXbrKdQ9FtAoesrzqZ0dE72qfQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);